---
- name: apt get update
  apt: update_cache=yes

- name: Install nginx
  apt: name=nginx state=present

# Ref: https://bugs.launchpad.net/ubuntu/+source/nginx/+bug/1581864
- name: Fix NGINX Debian bug.
  shell: |
    mkdir /etc/systemd/system/nginx.service.d;
    printf "[Service]\nExecStartPost=/bin/sleep 0.1\n" > /etc/systemd/system/nginx.service.d/override.conf
  become: true
  become_user: root
